[package]
name = "thinclippy"
version = "0.2.0"
authors = ["petrSchreiber <petrschreiber@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = "1.0.5"
structopt = { version = "0.2", default-features = false }
